#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias java6="export JAVA_HOME=$(/usr/libexec/java_home -v 1.6)"
alias java7="export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)"
# alias java8="export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)"

java7

